### ISSUE TITLE
Sent messages are blocked by anti-spam

### ISSUE THREAD

**Issue by wornout** [textpattern/com_connect#59]
For some reasons all messages sent by com_connect are blocked by anti-spam of sender email server (I presume).
Tech support told me that the error is:

> spam_content_r6_script_reject, in other words, some content of message body is detected as spam and refused. Probably is the name of the script used for sending message. Try to modify the script to make it more anonymous.

Some suggestions?

**Comment by Bloke** [comment]
> Try to modify the script to make it more anonymous.

Haha! Because making email anonymous reduces spam... right.

We get this every now and again with some servers, or some email providers (hotmail, gmail, yahoo, etc). You could try tweaking the 'SMTP envelope sender address' setting in Prefs->Admin. The plugin should use that if it's set. Might help.

You could also look into configuring SPF or DKIM on your host so that messages sent from the domain are tagged as more trustworthy. The way to do this is host-dependent so I cannot unfortunately offer any advice here.

Beyond that, we're at the mercy of email providers. Looking into the feasibility of [SMTP email in core](https://forum.textpattern.io/viewtopic.php?id=48031). Or you can write a small plugin module to interface with this plugin that could:

a. tweak the headers / content before delivery.
b. authenticate to SMTP.
c. use a third party mail service like MailChimp for delivery.
d. ...

If you went with option c), the companion pluign adi_contact has that built in, or I have a mailchimp module available. Although it uses the old API and I haven't got round to updating it.
