### ISSUE TITLE
Remove label

### ISSUE THREAD

**Issue by dragondz** [textpattern/com_connect#66]
Hi

Another feature request is removing label on input, a lot of design are using placeholder instead of label, then it s anoying to use css to hide it

**Comment by Bloke** [comment]
You can use `label=""` to remove it. But be sure to specify a `name` in its place otherwise your field won't have an identity.

**Comment by dragondz** [comment]
Hi Stef,

The problem with putting label="" is when receiving the email there is no label on them!

Cheers.

**Comment by Bloke** [comment]
Nope, you're right. Nothing comes through without the `label`; not even if you specify `name` in the default message body.

Hmmm. Not sure if we should automatically use the name as the email prefix label if there is no `label` set, or if we should respect the designer's choice of not showing it at all, and find another way to fall back.

You always have the option of designing the email template using the `body_form` attribute and plugging the values in. That should work fine.

How should we approach this:

1) Leave it alone - the `body_form` attribute suffices for such cases.
2) Introduce some flag attribute to control this behaviour, like `display_label` and set it true by default. Bonus points for being able to override it on the containing `<txp:com_connect>` tag for all contained tags.
3) Automatically fall back on the `name` field (although that might backfire with things like checkboxes/radios because their name is auto-generated in some cases, I think).
4) Introduce a new attribute that can be used as the field label that appears in the email. Defaults to label unless this overrides it.
5) Something else...

**Comment by dragondz** [comment]
Hi, I am not sure what s the easiest manner to do it but things should stay simple, the 2 is good for me, but maybe we should ask others on the community to see what they are thinking of ?

**Comment by Bloke** [comment]
[Okay](https://forum.textpattern.io/viewtopic.php?pid=315555#p315555)
